#if !canImport(ObjectiveC)
import XCTest

extension CodingAuthInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthInfoTests = [
        ("testCodingAuthInfo", testCodingAuthInfo),
    ]
}

extension CodingAuthorizationCodeFlowManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthorizationCodeFlowManagerTests = [
        ("testCodingAuthorizationCodeFlowManager", testCodingAuthorizationCodeFlowManager),
    ]
}

extension CodingAuthorizationCodeFlowPKCEManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthorizationCodeFlowPKCEManagerTests = [
        ("testCodingAuthorizationCodeFlowManager", testCodingAuthorizationCodeFlowManager),
    ]
}

extension CodingClientCredentialsFlowManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingClientCredentialsFlowManagerTests = [
        ("testCodingClientCredentialsFlowManager", testCodingClientCredentialsFlowManager),
    ]
}

extension CodingCurrentlyPlayingContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingCurrentlyPlayingContextTests = [
        ("testCodingCurrentlyPlayingContext", testCodingCurrentlyPlayingContext),
    ]
}

extension CodingPlaybackRequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingPlaybackRequestTests = [
        ("testCodingPlaybackReqest", testCodingPlaybackReqest),
    ]
}

extension CodingTimeReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTimeReferenceTests = [
        ("testCodingTimeReference", testCodingTimeReference),
    ]
}

extension CodingTrackAttributesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTrackAttributesTests = [
        ("testCodingTrackAttributes", testCodingTrackAttributes),
    ]
}

extension ExampleContentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleContentTests = [
        ("testAadioAnalysis", testAadioAnalysis),
        ("testAlbums", testAlbums),
        ("testArtists", testArtists),
        ("testAudioFeatures", testAudioFeatures),
        ("testBrowse", testBrowse),
        ("testEpisodes", testEpisodes),
        ("testLibrary", testLibrary),
        ("testPlayer", testPlayer),
        ("testPlaylistItems", testPlaylistItems),
        ("testPlaylists", testPlaylists),
        ("testSearch", testSearch),
        ("testShows", testShows),
        ("testTracks", testTracks),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowAlbumsTests = [
        ("testAlbumJinx", testAlbumJinx),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowAuthorizationTests = [
        ("testConvenienceInitializer", testConvenienceInitializer),
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
        ("testInvalidState1", testInvalidState1),
        ("testInvalidState2", testInvalidState2),
        ("testInvalidState3", testInvalidState3),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowBrowseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowBrowseTests = [
        ("testCategories", testCategories),
        ("testCategory", testCategory),
        ("testCategoryPlaylists", testCategoryPlaylists),
        ("testFeaturedPlaylists", testFeaturedPlaylists),
        ("testNewAlbumReleases", testNewAlbumReleases),
        ("testRecommendations", testRecommendations),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowEpisodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowEpisodeTests = [
        ("testEpisode", testEpisode),
        ("testEpisodes", testEpisodes),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowFollowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowFollowTests = [
        ("testFollowArtists", testFollowArtists),
        ("testFollowPlaylist", testFollowPlaylist),
        ("testFollowUsers", testFollowUsers),
        ("testUsersFollowPlaylist", testUsersFollowPlaylist),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests = [
        ("testAlbumJinx", testAlbumJinx),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests = [
        ("testConvenienceInitializer", testConvenienceInitializer),
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
        ("testInvalidState1", testInvalidState1),
        ("testInvalidState2", testInvalidState2),
        ("testInvalidState3", testInvalidState3),
        ("testInvalidState4", testInvalidState4),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests = [
        ("testCategories", testCategories),
        ("testCategory", testCategory),
        ("testCategoryPlaylists", testCategoryPlaylists),
        ("testFeaturedPlaylists", testFeaturedPlaylists),
        ("testNewAlbumReleases", testNewAlbumReleases),
        ("testRecommendations", testRecommendations),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEFollowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEFollowTests = [
        ("testFollowArtists", testFollowArtists),
        ("testFollowPlaylist", testFollowPlaylist),
        ("testFollowUsers", testFollowUsers),
        ("testUsersFollowPlaylist", testUsersFollowPlaylist),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests = [
        ("testCurrentUserTopArtists", testCurrentUserTopArtists),
        ("testCurrentUserTopArtistsLongTerm", testCurrentUserTopArtistsLongTerm),
        ("testCurrentUserTopArtistsMediumTerm", testCurrentUserTopArtistsMediumTerm),
        ("testCurrentUserTopArtistsShortTerm", testCurrentUserTopArtistsShortTerm),
        ("testCurrentUserTopTracks", testCurrentUserTopTracks),
        ("testCurrentUserTopTracksLongTerm", testCurrentUserTopTracksLongTerm),
        ("testCurrentUserTopTracksMediumTerm", testCurrentUserTopTracksMediumTerm),
        ("testCurrentUserTopTracksShortTerm", testCurrentUserTopTracksShortTerm),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests = [
        ("testAddToQueue", testAddToQueue),
        ("testPlayAndCurrentPlaybackForEpisode", testPlayAndCurrentPlaybackForEpisode),
        ("testPlayback", testPlayback),
        ("testPlayHistory", testPlayHistory),
        ("testPlayPause", testPlayPause),
        ("testPlaySeekToPositionAndSetVolume", testPlaySeekToPositionAndSetVolume),
        ("testPlaySkipToNextAndPrevious", testPlaySkipToNextAndPrevious),
        ("testRepeatMode", testRepeatMode),
        ("testShuffle", testShuffle),
        ("testSingleTrackPlayback", testSingleTrackPlayback),
        ("testTransferPlayback", testTransferPlayback),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests = [
        ("testCreatePlaylistAddRemoveReorderItems", testCreatePlaylistAddRemoveReorderItems),
        ("testCreatePlaylistAndAddTracksThenUnfollowIt", testCreatePlaylistAndAddTracksThenUnfollowIt),
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testFilteredPlaylistItems", testFilteredPlaylistItems),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistImage", testPlaylistImage),
        ("testPlaylistWithEpisodesAndLocalTracks", testPlaylistWithEpisodesAndLocalTracks),
        ("testRemoveAllOccurencesFromPlaylist", testRemoveAllOccurencesFromPlaylist),
        ("testRemoveSpecificOccurencesFromPlaylist", testRemoveSpecificOccurencesFromPlaylist),
        ("testReplaceItemsInPlaylist", testReplaceItemsInPlaylist),
        ("testUploadPlaylistImage", testUploadPlaylistImage),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests = [
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEShowTests = [
        ("testShow", testShow),
        ("testShowEpisodes", testShowEpisodes),
        ("testShows", testShows),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCETrackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCETrackTests = [
        ("testTrack", testTrack),
        ("testTrackAudioAnalysis", testTrackAudioAnalysis),
        ("testTrackAudioFeatures", testTrackAudioFeatures),
        ("testTrackLink", testTrackLink),
        ("testTracks", testTracks),
        ("testTracksAudioFeatures", testTracksAudioFeatures),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests = [
        ("testCurrentUserProfile", testCurrentUserProfile),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEpisodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEpisodeTests = [
        ("testEpisode", testEpisode),
        ("testEpisodes", testEpisodes),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPersonalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPersonalizationTests = [
        ("testCurrentUserTopArtists", testCurrentUserTopArtists),
        ("testCurrentUserTopArtistsLongTerm", testCurrentUserTopArtistsLongTerm),
        ("testCurrentUserTopArtistsMediumTerm", testCurrentUserTopArtistsMediumTerm),
        ("testCurrentUserTopArtistsShortTerm", testCurrentUserTopArtistsShortTerm),
        ("testCurrentUserTopTracks", testCurrentUserTopTracks),
        ("testCurrentUserTopTracksLongTerm", testCurrentUserTopTracksLongTerm),
        ("testCurrentUserTopTracksMediumTerm", testCurrentUserTopTracksMediumTerm),
        ("testCurrentUserTopTracksShortTerm", testCurrentUserTopTracksShortTerm),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPlayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPlayerTests = [
        ("testAddToQueue", testAddToQueue),
        ("testPlayAndCurrentPlaybackForEpisode", testPlayAndCurrentPlaybackForEpisode),
        ("testPlayback", testPlayback),
        ("testPlayHistory", testPlayHistory),
        ("testPlayPause", testPlayPause),
        ("testPlaySeekToPositionAndSetVolume", testPlaySeekToPositionAndSetVolume),
        ("testPlaySkipToNextAndPrevious", testPlaySkipToNextAndPrevious),
        ("testRepeatMode", testRepeatMode),
        ("testShuffle", testShuffle),
        ("testSingleTrackPlayback", testSingleTrackPlayback),
        ("testTransferPlayback", testTransferPlayback),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPlaylistsTests = [
        ("testCreatePlaylistAddRemoveReorderItems", testCreatePlaylistAddRemoveReorderItems),
        ("testCreatePlaylistAndAddTracksThenUnfollowIt", testCreatePlaylistAndAddTracksThenUnfollowIt),
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testFilteredPlaylistItems", testFilteredPlaylistItems),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistImage", testPlaylistImage),
        ("testPlaylistWithEpisodesAndLocalTracks", testPlaylistWithEpisodesAndLocalTracks),
        ("testRemoveAllOccurencesFromPlaylist", testRemoveAllOccurencesFromPlaylist),
        ("testRemoveSpecificOccurencesFromPlaylist", testRemoveSpecificOccurencesFromPlaylist),
        ("testReplaceItemsInPlaylist", testReplaceItemsInPlaylist),
        ("testUploadPlaylistImage", testUploadPlaylistImage),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests = [
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowShowTests = [
        ("testShow", testShow),
        ("testShowEpisodes", testShowEpisodes),
        ("testShows", testShows),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowTrackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowTrackTests = [
        ("testTrack", testTrack),
        ("testTrackAudioAnalysis", testTrackAudioAnalysis),
        ("testTrackAudioFeatures", testTrackAudioFeatures),
        ("testTrackLink", testTrackLink),
        ("testTracks", testTracks),
        ("testTracksAudioFeatures", testTracksAudioFeatures),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowUserProfileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowUserProfileTests = [
        ("testCurrentUserProfile", testCurrentUserProfile),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIClientCredentialsFlowAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowAlbumsTests = [
        ("testAlbumJinx", testAlbumJinx),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
    ]
}

extension SpotifyAPIClientCredentialsFlowArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIClientCredentialsFlowAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowAuthorizationTests = [
        ("testConvenienceInitializer", testConvenienceInitializer),
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
    ]
}

extension SpotifyAPIClientCredentialsFlowBrowseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowBrowseTests = [
        ("testCategories", testCategories),
        ("testCategory", testCategory),
        ("testCategoryPlaylists", testCategoryPlaylists),
        ("testFeaturedPlaylists", testFeaturedPlaylists),
        ("testNewAlbumReleases", testNewAlbumReleases),
        ("testRecommendations", testRecommendations),
    ]
}

extension SpotifyAPIClientCredentialsFlowEpisodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowEpisodeTests = [
        ("testEpisode", testEpisode),
        ("testEpisodes", testEpisodes),
    ]
}

extension SpotifyAPIClientCredentialsFlowFollowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowFollowTests = [
        ("testUsersFollowPlaylist", testUsersFollowPlaylist),
    ]
}

extension SpotifyAPIClientCredentialsFlowPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowPlaylistsTests = [
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testFilteredPlaylistItems", testFilteredPlaylistItems),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistWithEpisodesAndLocalTracks", testPlaylistWithEpisodesAndLocalTracks),
    ]
}

extension SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests = [
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIClientCredentialsFlowShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowShowTests = [
        ("testShow", testShow),
        ("testShowEpisodes", testShowEpisodes),
        ("testShows", testShows),
    ]
}

extension SpotifyAPIClientCredentialsFlowTrackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowTrackTests = [
        ("testTrack", testTrack),
        ("testTrackAudioAnalysis", testTrackAudioAnalysis),
        ("testTrackAudioFeatures", testTrackAudioFeatures),
        ("testTrackLink", testTrackLink),
        ("testTracks", testTracks),
        ("testTracksAudioFeatures", testTracksAudioFeatures),
    ]
}

extension SpotifyAPIClientCredentialsFlowUserProfileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowUserProfileTests = [
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyIdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyIdentifierTests = [
        ("testAlbumURIs", testAlbumURIs),
        ("testArtistURIs", testArtistURIs),
        ("testEpisodeURIs", testEpisodeURIs),
        ("testInvalidURIs", testInvalidURIs),
        ("testPlaylistURIs", testPlaylistURIs),
        ("testShowURIs", testShowURIs),
        ("testTrackURIs", testTrackURIs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodingAuthInfoTests.__allTests__CodingAuthInfoTests),
        testCase(CodingAuthorizationCodeFlowManagerTests.__allTests__CodingAuthorizationCodeFlowManagerTests),
        testCase(CodingAuthorizationCodeFlowPKCEManagerTests.__allTests__CodingAuthorizationCodeFlowPKCEManagerTests),
        testCase(CodingClientCredentialsFlowManagerTests.__allTests__CodingClientCredentialsFlowManagerTests),
        testCase(CodingCurrentlyPlayingContextTests.__allTests__CodingCurrentlyPlayingContextTests),
        testCase(CodingPlaybackRequestTests.__allTests__CodingPlaybackRequestTests),
        testCase(CodingTimeReferenceTests.__allTests__CodingTimeReferenceTests),
        testCase(CodingTrackAttributesTests.__allTests__CodingTrackAttributesTests),
        testCase(ExampleContentTests.__allTests__ExampleContentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowAlbumsTests.__allTests__SpotifyAPIAuthorizationCodeFlowAlbumsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowArtistTests.__allTests__SpotifyAPIAuthorizationCodeFlowArtistTests),
        testCase(SpotifyAPIAuthorizationCodeFlowAuthorizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowAuthorizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowBrowseTests.__allTests__SpotifyAPIAuthorizationCodeFlowBrowseTests),
        testCase(SpotifyAPIAuthorizationCodeFlowEpisodeTests.__allTests__SpotifyAPIAuthorizationCodeFlowEpisodeTests),
        testCase(SpotifyAPIAuthorizationCodeFlowFollowTests.__allTests__SpotifyAPIAuthorizationCodeFlowFollowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEArtistTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEArtistTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEFollowTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEFollowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEShowTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEShowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCETrackTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCETrackTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEpisodeTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEpisodeTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPersonalizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPersonalizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPlayerTests.__allTests__SpotifyAPIAuthorizationCodeFlowPlayerTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPlaylistsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPlaylistsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests.__allTests__SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowShowTests.__allTests__SpotifyAPIAuthorizationCodeFlowShowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowTrackTests.__allTests__SpotifyAPIAuthorizationCodeFlowTrackTests),
        testCase(SpotifyAPIAuthorizationCodeFlowUserProfileTests.__allTests__SpotifyAPIAuthorizationCodeFlowUserProfileTests),
        testCase(SpotifyAPIClientCredentialsFlowAlbumsTests.__allTests__SpotifyAPIClientCredentialsFlowAlbumsTests),
        testCase(SpotifyAPIClientCredentialsFlowArtistTests.__allTests__SpotifyAPIClientCredentialsFlowArtistTests),
        testCase(SpotifyAPIClientCredentialsFlowAuthorizationTests.__allTests__SpotifyAPIClientCredentialsFlowAuthorizationTests),
        testCase(SpotifyAPIClientCredentialsFlowBrowseTests.__allTests__SpotifyAPIClientCredentialsFlowBrowseTests),
        testCase(SpotifyAPIClientCredentialsFlowEpisodeTests.__allTests__SpotifyAPIClientCredentialsFlowEpisodeTests),
        testCase(SpotifyAPIClientCredentialsFlowFollowTests.__allTests__SpotifyAPIClientCredentialsFlowFollowTests),
        testCase(SpotifyAPIClientCredentialsFlowPlaylistsTests.__allTests__SpotifyAPIClientCredentialsFlowPlaylistsTests),
        testCase(SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests.__allTests__SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests),
        testCase(SpotifyAPIClientCredentialsFlowShowTests.__allTests__SpotifyAPIClientCredentialsFlowShowTests),
        testCase(SpotifyAPIClientCredentialsFlowTrackTests.__allTests__SpotifyAPIClientCredentialsFlowTrackTests),
        testCase(SpotifyAPIClientCredentialsFlowUserProfileTests.__allTests__SpotifyAPIClientCredentialsFlowUserProfileTests),
        testCase(SpotifyIdentifierTests.__allTests__SpotifyIdentifierTests),
    ]
}
#endif
