#if !canImport(ObjectiveC)
import XCTest

extension AuthorizationScopesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthorizationScopesTests = [
        ("testAllScopes", testAllScopes),
        ("testEmptyScopes", testEmptyScopes),
        ("testScopes", testScopes),
        ("testVariadicScopes", testVariadicScopes),
    ]
}

extension CodingAuthInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthInfoTests = [
        ("testCodingAuthInfo", testCodingAuthInfo),
    ]
}

extension CodingAuthorizationCodeFlowManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthorizationCodeFlowManagerTests = [
        ("testCodingAuthorizationCodeFlowManager", testCodingAuthorizationCodeFlowManager),
    ]
}

extension CodingAuthorizationCodeFlowPKCEManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthorizationCodeFlowPKCEManagerTests = [
        ("testCodingAuthorizationCodeFlowManager", testCodingAuthorizationCodeFlowManager),
    ]
}

extension CodingClientCredentialsFlowManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingClientCredentialsFlowManagerTests = [
        ("testCodingClientCredentialsFlowManager", testCodingClientCredentialsFlowManager),
    ]
}

extension CodingCurrentlyPlayingContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingCurrentlyPlayingContextTests = [
        ("testCodingCurrentlyPlayingContext", testCodingCurrentlyPlayingContext),
    ]
}

extension CodingPlaybackRequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingPlaybackRequestTests = [
        ("testCodingContextOption1", testCodingContextOption1),
        ("testCodingContextOption2", testCodingContextOption2),
        ("testCodingOffsetOption1", testCodingOffsetOption1),
        ("testCodingOffsetOption2", testCodingOffsetOption2),
        ("testCodingPlaybackReqest10", testCodingPlaybackReqest10),
        ("testCodingPlaybackReqest11", testCodingPlaybackReqest11),
        ("testCodingPlaybackReqest12", testCodingPlaybackReqest12),
        ("testCodingPlaybackReqest13", testCodingPlaybackReqest13),
        ("testCodingPlaybackReqest14", testCodingPlaybackReqest14),
        ("testCodingPlaybackReqest1", testCodingPlaybackReqest1),
        ("testCodingPlaybackReqest2", testCodingPlaybackReqest2),
        ("testCodingPlaybackReqest3", testCodingPlaybackReqest3),
        ("testCodingPlaybackReqest4", testCodingPlaybackReqest4),
        ("testCodingPlaybackReqest5", testCodingPlaybackReqest5),
        ("testCodingPlaybackReqest6", testCodingPlaybackReqest6),
        ("testCodingPlaybackReqest7", testCodingPlaybackReqest7),
        ("testCodingPlaybackReqest8", testCodingPlaybackReqest8),
        ("testCodingPlaybackReqest9", testCodingPlaybackReqest9),
        ("testCodingPlaybackReqestSingleTrack", testCodingPlaybackReqestSingleTrack),
        ("testCodingPlaybackReqestSingleTrackWithPositionMS", testCodingPlaybackReqestSingleTrackWithPositionMS),
    ]
}

extension CodingSpotifyUserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingSpotifyUserTests = [
        ("testCodingCurrentSpotifyUser", testCodingCurrentSpotifyUser),
        ("testCodingOtherUserProfile", testCodingOtherUserProfile),
    ]
}

extension CodingTimeReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTimeReferenceTests = [
        ("testCodingTimeReference", testCodingTimeReference),
    ]
}

extension CodingTrackAttributesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTrackAttributesTests = [
        ("testCodingTrackAttributesFull", testCodingTrackAttributesFull),
        ("testCodingTrackAttributesSmall", testCodingTrackAttributesSmall),
    ]
}

extension CursorPagingObjectPlayHistoryCodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CursorPagingObjectPlayHistoryCodingTests = [
        ("testCoding", testCoding),
    ]
}

extension ExampleContentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleContentTests = [
        ("testAadioAnalysis", testAadioAnalysis),
        ("testAlbums", testAlbums),
        ("testArtists", testArtists),
        ("testAudioFeatures", testAudioFeatures),
        ("testBrowse", testBrowse),
        ("testEpisodes", testEpisodes),
        ("testLibrary", testLibrary),
        ("testPlayer", testPlayer),
        ("testPlaylistItems", testPlaylistItems),
        ("testPlaylists", testPlaylists),
        ("testSearch", testSearch),
        ("testShows", testShows),
        ("testTracks", testTracks),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowAlbumsTests = [
        ("testAlbumJinx", testAlbumJinx),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
        ("testTheLongestAlbumTracks2", testTheLongestAlbumTracks2),
        ("testTheLongestAlbumTracksCollect", testTheLongestAlbumTracksCollect),
        ("testTheLongestAlbumTracksConcurrent", testTheLongestAlbumTracksConcurrent),
        ("testTheLongestAlbumTracksConcurrent2", testTheLongestAlbumTracksConcurrent2),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsExtendSinglePageConcurrent", testArtistAlbumsExtendSinglePageConcurrent),
        ("testArtistAlbumsExtendSinglePageSerial", testArtistAlbumsExtendSinglePageSerial),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowAuthorizationTests = [
        ("testCodingSpotifyAPI", testCodingSpotifyAPI),
        ("testConvenienceInitializer", testConvenienceInitializer),
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
        ("testInvalidState1", testInvalidState1),
        ("testInvalidState2", testInvalidState2),
        ("testInvalidState3", testInvalidState3),
        ("testReassigningAuthorizationManager", testReassigningAuthorizationManager),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowBrowseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowBrowseTests = [
        ("testCategories", testCategories),
        ("testCategory", testCategory),
        ("testCategoryPlaylists", testCategoryPlaylists),
        ("testFeaturedPlaylists", testFeaturedPlaylists),
        ("testNewAlbumReleases", testNewAlbumReleases),
        ("testRecommendations", testRecommendations),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowEpisodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowEpisodeTests = [
        ("testEpisode", testEpisode),
        ("testEpisodes", testEpisodes),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowErrorTests = [
        ("testAutoRetryOnRateLimitedErrorConcurrent", testAutoRetryOnRateLimitedErrorConcurrent),
        ("testAutoRetryOnRateLimitedErrorSerial", testAutoRetryOnRateLimitedErrorSerial),
        ("testDecodeSpotifyErrorFromInvalidAlbumURI", testDecodeSpotifyErrorFromInvalidAlbumURI),
        ("testDecodeSpotifyPlayerError", testDecodeSpotifyPlayerError),
        ("testExceedRetryLimit", testExceedRetryLimit),
        ("testNonRetryableErrors", testNonRetryableErrors),
        ("testRetryOnSpotifyErrors", testRetryOnSpotifyErrors),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowFollowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowFollowTests = [
        ("testFollowArtists", testFollowArtists),
        ("testFollowPlaylist", testFollowPlaylist),
        ("testFollowUsers", testFollowUsers),
        ("testUsersFollowPlaylist", testUsersFollowPlaylist),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowInsufficientScopeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowInsufficientScopeTests = [
        ("testInsufficientScope2", testInsufficientScope2),
        ("testInsufficientScopeLocal", testInsufficientScopeLocal),
        ("testMakeRequestWithoutAuthorization", testMakeRequestWithoutAuthorization),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowLibraryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowLibraryTests = [
        ("testSaveAlbums", testSaveAlbums),
        ("testSaveEpisodes", testSaveEpisodes),
        ("testSaveShows", testSaveShows),
        ("testSaveTracks", testSaveTracks),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowMarketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowMarketTests = [
        ("testAvailableMarkets", testAvailableMarkets),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests = [
        ("testAlbumJinx", testAlbumJinx),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
        ("testTheLongestAlbumTracks2", testTheLongestAlbumTracks2),
        ("testTheLongestAlbumTracksCollect", testTheLongestAlbumTracksCollect),
        ("testTheLongestAlbumTracksConcurrent", testTheLongestAlbumTracksConcurrent),
        ("testTheLongestAlbumTracksConcurrent2", testTheLongestAlbumTracksConcurrent2),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsExtendSinglePageConcurrent", testArtistAlbumsExtendSinglePageConcurrent),
        ("testArtistAlbumsExtendSinglePageSerial", testArtistAlbumsExtendSinglePageSerial),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests = [
        ("testCodingSpotifyAPI", testCodingSpotifyAPI),
        ("testConvenienceInitializer", testConvenienceInitializer),
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
        ("testInvalidCodeVerifier", testInvalidCodeVerifier),
        ("testInvalidState1", testInvalidState1),
        ("testInvalidState2", testInvalidState2),
        ("testInvalidState3", testInvalidState3),
        ("testReassigningAuthorizationManager", testReassigningAuthorizationManager),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests = [
        ("testCategories", testCategories),
        ("testCategory", testCategory),
        ("testCategoryPlaylists", testCategoryPlaylists),
        ("testFeaturedPlaylists", testFeaturedPlaylists),
        ("testNewAlbumReleases", testNewAlbumReleases),
        ("testRecommendations", testRecommendations),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEEpisodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEEpisodeTests = [
        ("testEpisode", testEpisode),
        ("testEpisodes", testEpisodes),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEErrorTests = [
        ("testAutoRetryOnRateLimitedErrorConcurrent", testAutoRetryOnRateLimitedErrorConcurrent),
        ("testAutoRetryOnRateLimitedErrorSerial", testAutoRetryOnRateLimitedErrorSerial),
        ("testDecodeSpotifyErrorFromInvalidAlbumURI", testDecodeSpotifyErrorFromInvalidAlbumURI),
        ("testDecodeSpotifyPlayerError", testDecodeSpotifyPlayerError),
        ("testExceedRetryLimit", testExceedRetryLimit),
        ("testNonRetryableErrors", testNonRetryableErrors),
        ("testRetryOnSpotifyErrors", testRetryOnSpotifyErrors),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEFollowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEFollowTests = [
        ("testFollowArtists", testFollowArtists),
        ("testFollowPlaylist", testFollowPlaylist),
        ("testFollowUsers", testFollowUsers),
        ("testUsersFollowPlaylist", testUsersFollowPlaylist),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEInsufficientScopeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEInsufficientScopeTests = [
        ("testInsufficientScope2", testInsufficientScope2),
        ("testInsufficientScopeLocal", testInsufficientScopeLocal),
        ("testMakeRequestWithoutAuthorization", testMakeRequestWithoutAuthorization),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCELibraryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCELibraryTests = [
        ("testSaveAlbums", testSaveAlbums),
        ("testSaveEpisodes", testSaveEpisodes),
        ("testSaveShows", testSaveShows),
        ("testSaveTracks", testSaveTracks),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEMarketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEMarketTests = [
        ("testAvailableMarkets", testAvailableMarkets),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests = [
        ("testCurrentUserTopArtists", testCurrentUserTopArtists),
        ("testCurrentUserTopArtistsLongTerm", testCurrentUserTopArtistsLongTerm),
        ("testCurrentUserTopArtistsMediumTerm", testCurrentUserTopArtistsMediumTerm),
        ("testCurrentUserTopArtistsShortTerm", testCurrentUserTopArtistsShortTerm),
        ("testCurrentUserTopTracks", testCurrentUserTopTracks),
        ("testCurrentUserTopTracksLongTerm", testCurrentUserTopTracksLongTerm),
        ("testCurrentUserTopTracksMediumTerm", testCurrentUserTopTracksMediumTerm),
        ("testCurrentUserTopTracksShortTerm", testCurrentUserTopTracksShortTerm),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests = [
        ("testAddToQueue", testAddToQueue),
        ("testPlayAndCurrentPlaybackForEpisode", testPlayAndCurrentPlaybackForEpisode),
        ("testPlayback", testPlayback),
        ("testPlayHistory", testPlayHistory),
        ("testPlayPause", testPlayPause),
        ("testPlaySeekToPositionAndSetVolume", testPlaySeekToPositionAndSetVolume),
        ("testPlaySkipToNextAndPrevious", testPlaySkipToNextAndPrevious),
        ("testRepeatMode", testRepeatMode),
        ("testShuffle", testShuffle),
        ("testSingleTrackPlayback", testSingleTrackPlayback),
        ("testTransferPlayback", testTransferPlayback),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests = [
        ("testCreatePlaylistAddRemoveReorderItems", testCreatePlaylistAddRemoveReorderItems),
        ("testCreatePlaylistAndAddTracksThenUnfollowIt", testCreatePlaylistAndAddTracksThenUnfollowIt),
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testFilteredPlaylistItems", testFilteredPlaylistItems),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistImage", testPlaylistImage),
        ("testPlaylistWithEpisodesAndLocalTracks", testPlaylistWithEpisodesAndLocalTracks),
        ("testRemoveAllOccurencesFromPlaylist", testRemoveAllOccurencesFromPlaylist),
        ("testRemoveSpecificOccurencesFromPlaylist", testRemoveSpecificOccurencesFromPlaylist),
        ("testReplaceItemsInPlaylist", testReplaceItemsInPlaylist),
        ("testUploadPlaylistImage", testUploadPlaylistImage),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests = [
        ("testConcurrentRequestsWithExpiredToken", testConcurrentRequestsWithExpiredToken),
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCESearchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCESearchTests = [
        ("testFilteredSearchForAbbeyRoad", testFilteredSearchForAbbeyRoad),
        ("testFilteredSearchNoMatches", testFilteredSearchNoMatches),
        ("testInvalidCategories", testInvalidCategories),
        ("testSearchAllCategories", testSearchAllCategories),
        ("testSearchEpisodesShowsNoMarket", testSearchEpisodesShowsNoMarket),
        ("testSpecificTrackSearch", testSpecificTrackSearch),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEShowTests = [
        ("testShow", testShow),
        ("testShowEpisodes", testShowEpisodes),
        ("testShowEpisodesExtendPagesConcurrent", testShowEpisodesExtendPagesConcurrent),
        ("testShows", testShows),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCETrackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCETrackTests = [
        ("testInvalidIdCategories", testInvalidIdCategories),
        ("testTrack", testTrack),
        ("testTrackAudioAnalysis", testTrackAudioAnalysis),
        ("testTrackAudioFeatures", testTrackAudioFeatures),
        ("testTrackLink", testTrackLink),
        ("testTracks", testTracks),
        ("testTracksAudioFeatures", testTracksAudioFeatures),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests = [
        ("testCurrentUserProfile", testCurrentUserProfile),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPersonalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPersonalizationTests = [
        ("testCurrentUserTopArtists", testCurrentUserTopArtists),
        ("testCurrentUserTopArtistsLongTerm", testCurrentUserTopArtistsLongTerm),
        ("testCurrentUserTopArtistsMediumTerm", testCurrentUserTopArtistsMediumTerm),
        ("testCurrentUserTopArtistsShortTerm", testCurrentUserTopArtistsShortTerm),
        ("testCurrentUserTopTracks", testCurrentUserTopTracks),
        ("testCurrentUserTopTracksLongTerm", testCurrentUserTopTracksLongTerm),
        ("testCurrentUserTopTracksMediumTerm", testCurrentUserTopTracksMediumTerm),
        ("testCurrentUserTopTracksShortTerm", testCurrentUserTopTracksShortTerm),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPlayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPlayerTests = [
        ("testAddToQueue", testAddToQueue),
        ("testPlayAndCurrentPlaybackForEpisode", testPlayAndCurrentPlaybackForEpisode),
        ("testPlayback", testPlayback),
        ("testPlayHistory", testPlayHistory),
        ("testPlayPause", testPlayPause),
        ("testPlaySeekToPositionAndSetVolume", testPlaySeekToPositionAndSetVolume),
        ("testPlaySkipToNextAndPrevious", testPlaySkipToNextAndPrevious),
        ("testRepeatMode", testRepeatMode),
        ("testShuffle", testShuffle),
        ("testSingleTrackPlayback", testSingleTrackPlayback),
        ("testTransferPlayback", testTransferPlayback),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPlaylistsTests = [
        ("testCreatePlaylistAddRemoveReorderItems", testCreatePlaylistAddRemoveReorderItems),
        ("testCreatePlaylistAndAddTracksThenUnfollowIt", testCreatePlaylistAndAddTracksThenUnfollowIt),
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testFilteredPlaylistItems", testFilteredPlaylistItems),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistImage", testPlaylistImage),
        ("testPlaylistWithEpisodesAndLocalTracks", testPlaylistWithEpisodesAndLocalTracks),
        ("testRemoveAllOccurencesFromPlaylist", testRemoveAllOccurencesFromPlaylist),
        ("testRemoveSpecificOccurencesFromPlaylist", testRemoveSpecificOccurencesFromPlaylist),
        ("testReplaceItemsInPlaylist", testReplaceItemsInPlaylist),
        ("testUploadPlaylistImage", testUploadPlaylistImage),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests = [
        ("testConcurrentRequestsWithExpiredToken", testConcurrentRequestsWithExpiredToken),
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowSearchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowSearchTests = [
        ("testFilteredSearchForAbbeyRoad", testFilteredSearchForAbbeyRoad),
        ("testFilteredSearchNoMatches", testFilteredSearchNoMatches),
        ("testInvalidCategories", testInvalidCategories),
        ("testSearchAllCategories", testSearchAllCategories),
        ("testSearchEpisodesShowsNoMarket", testSearchEpisodesShowsNoMarket),
        ("testSpecificTrackSearch", testSpecificTrackSearch),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowShowTests = [
        ("testShow", testShow),
        ("testShowEpisodes", testShowEpisodes),
        ("testShowEpisodesExtendPagesConcurrent", testShowEpisodesExtendPagesConcurrent),
        ("testShows", testShows),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowTrackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowTrackTests = [
        ("testInvalidIdCategories", testInvalidIdCategories),
        ("testTrack", testTrack),
        ("testTrackAudioAnalysis", testTrackAudioAnalysis),
        ("testTrackAudioFeatures", testTrackAudioFeatures),
        ("testTrackLink", testTrackLink),
        ("testTracks", testTracks),
        ("testTracksAudioFeatures", testTracksAudioFeatures),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowUserProfileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowUserProfileTests = [
        ("testCurrentUserProfile", testCurrentUserProfile),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIClientCredentialsFlowAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowAlbumsTests = [
        ("testAlbumJinx", testAlbumJinx),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
        ("testTheLongestAlbumTracks2", testTheLongestAlbumTracks2),
        ("testTheLongestAlbumTracksCollect", testTheLongestAlbumTracksCollect),
        ("testTheLongestAlbumTracksConcurrent", testTheLongestAlbumTracksConcurrent),
        ("testTheLongestAlbumTracksConcurrent2", testTheLongestAlbumTracksConcurrent2),
    ]
}

extension SpotifyAPIClientCredentialsFlowArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsExtendSinglePageConcurrent", testArtistAlbumsExtendSinglePageConcurrent),
        ("testArtistAlbumsExtendSinglePageSerial", testArtistAlbumsExtendSinglePageSerial),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIClientCredentialsFlowAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowAuthorizationTests = [
        ("testCodingSpotifyAPI", testCodingSpotifyAPI),
        ("testConvenienceInitializer", testConvenienceInitializer),
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
        ("testReassigningAuthorizationManager", testReassigningAuthorizationManager),
    ]
}

extension SpotifyAPIClientCredentialsFlowBrowseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowBrowseTests = [
        ("testCategories", testCategories),
        ("testCategory", testCategory),
        ("testCategoryPlaylists", testCategoryPlaylists),
        ("testFeaturedPlaylists", testFeaturedPlaylists),
        ("testNewAlbumReleases", testNewAlbumReleases),
        ("testRecommendations", testRecommendations),
    ]
}

extension SpotifyAPIClientCredentialsFlowEpisodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowEpisodeTests = [
        ("testEpisode", testEpisode),
        ("testEpisodes", testEpisodes),
    ]
}

extension SpotifyAPIClientCredentialsFlowErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowErrorTests = [
        ("testAutoRetryOnRateLimitedErrorConcurrent", testAutoRetryOnRateLimitedErrorConcurrent),
        ("testAutoRetryOnRateLimitedErrorSerial", testAutoRetryOnRateLimitedErrorSerial),
        ("testDecodeSpotifyErrorFromInvalidAlbumURI", testDecodeSpotifyErrorFromInvalidAlbumURI),
        ("testExceedRetryLimit", testExceedRetryLimit),
        ("testNonRetryableErrors", testNonRetryableErrors),
        ("testRetryOnSpotifyErrors", testRetryOnSpotifyErrors),
    ]
}

extension SpotifyAPIClientCredentialsFlowFollowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowFollowTests = [
        ("testUsersFollowPlaylist", testUsersFollowPlaylist),
    ]
}

extension SpotifyAPIClientCredentialsFlowMarketTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowMarketTests = [
        ("testAvailableMarkets", testAvailableMarkets),
    ]
}

extension SpotifyAPIClientCredentialsFlowPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowPlaylistsTests = [
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testFilteredPlaylistItems", testFilteredPlaylistItems),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistWithEpisodesAndLocalTracks", testPlaylistWithEpisodesAndLocalTracks),
    ]
}

extension SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests = [
        ("testConcurrentRequestsWithExpiredToken", testConcurrentRequestsWithExpiredToken),
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIClientCredentialsFlowSearchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowSearchTests = [
        ("testFilteredSearchForAbbeyRoad", testFilteredSearchForAbbeyRoad),
        ("testFilteredSearchNoMatches", testFilteredSearchNoMatches),
        ("testInvalidCategories", testInvalidCategories),
        ("testSearchAllCategories", testSearchAllCategories),
        ("testSearchEpisodesShowsNoMarket", testSearchEpisodesShowsNoMarket),
        ("testSpecificTrackSearch", testSpecificTrackSearch),
    ]
}

extension SpotifyAPIClientCredentialsFlowShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowShowTests = [
        ("testShow", testShow),
        ("testShowEpisodes", testShowEpisodes),
        ("testShowEpisodesExtendPagesConcurrent", testShowEpisodesExtendPagesConcurrent),
        ("testShows", testShows),
    ]
}

extension SpotifyAPIClientCredentialsFlowTrackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowTrackTests = [
        ("testInvalidIdCategories", testInvalidIdCategories),
        ("testTrack", testTrack),
        ("testTrackAudioAnalysis", testTrackAudioAnalysis),
        ("testTrackAudioFeatures", testTrackAudioFeatures),
        ("testTrackLink", testTrackLink),
        ("testTracks", testTracks),
        ("testTracksAudioFeatures", testTracksAudioFeatures),
    ]
}

extension SpotifyAPIClientCredentialsFlowUserProfileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowUserProfileTests = [
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyIdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyIdentifierTests = [
        ("testAlbumURIs", testAlbumURIs),
        ("testArtistURIs", testArtistURIs),
        ("testEpisodeURIs", testEpisodeURIs),
        ("testInvalidURIs", testInvalidURIs),
        ("testPlaylistURIs", testPlaylistURIs),
        ("testShowURIs", testShowURIs),
        ("testTrackURIs", testTrackURIs),
    ]
}

extension SpotifyPlayerErrorCodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyPlayerErrorCodingTests = [
        ("testCodingVolumeControlDisallow", testCodingVolumeControlDisallow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AuthorizationScopesTests.__allTests__AuthorizationScopesTests),
        testCase(CodingAuthInfoTests.__allTests__CodingAuthInfoTests),
        testCase(CodingAuthorizationCodeFlowManagerTests.__allTests__CodingAuthorizationCodeFlowManagerTests),
        testCase(CodingAuthorizationCodeFlowPKCEManagerTests.__allTests__CodingAuthorizationCodeFlowPKCEManagerTests),
        testCase(CodingClientCredentialsFlowManagerTests.__allTests__CodingClientCredentialsFlowManagerTests),
        testCase(CodingCurrentlyPlayingContextTests.__allTests__CodingCurrentlyPlayingContextTests),
        testCase(CodingPlaybackRequestTests.__allTests__CodingPlaybackRequestTests),
        testCase(CodingSpotifyUserTests.__allTests__CodingSpotifyUserTests),
        testCase(CodingTimeReferenceTests.__allTests__CodingTimeReferenceTests),
        testCase(CodingTrackAttributesTests.__allTests__CodingTrackAttributesTests),
        testCase(CursorPagingObjectPlayHistoryCodingTests.__allTests__CursorPagingObjectPlayHistoryCodingTests),
        testCase(ExampleContentTests.__allTests__ExampleContentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowAlbumsTests.__allTests__SpotifyAPIAuthorizationCodeFlowAlbumsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowArtistTests.__allTests__SpotifyAPIAuthorizationCodeFlowArtistTests),
        testCase(SpotifyAPIAuthorizationCodeFlowAuthorizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowAuthorizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowBrowseTests.__allTests__SpotifyAPIAuthorizationCodeFlowBrowseTests),
        testCase(SpotifyAPIAuthorizationCodeFlowEpisodeTests.__allTests__SpotifyAPIAuthorizationCodeFlowEpisodeTests),
        testCase(SpotifyAPIAuthorizationCodeFlowErrorTests.__allTests__SpotifyAPIAuthorizationCodeFlowErrorTests),
        testCase(SpotifyAPIAuthorizationCodeFlowFollowTests.__allTests__SpotifyAPIAuthorizationCodeFlowFollowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowInsufficientScopeTests.__allTests__SpotifyAPIAuthorizationCodeFlowInsufficientScopeTests),
        testCase(SpotifyAPIAuthorizationCodeFlowLibraryTests.__allTests__SpotifyAPIAuthorizationCodeFlowLibraryTests),
        testCase(SpotifyAPIAuthorizationCodeFlowMarketTests.__allTests__SpotifyAPIAuthorizationCodeFlowMarketTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEArtistTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEArtistTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEBrowseTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEEpisodeTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEEpisodeTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEErrorTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEErrorTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEFollowTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEFollowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEInsufficientScopeTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEInsufficientScopeTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCELibraryTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCELibraryTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEMarketTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEMarketTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPersonalizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlayerTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCESearchTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCESearchTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEShowTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEShowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCETrackTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCETrackTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEUserProfileTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPersonalizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPersonalizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPlayerTests.__allTests__SpotifyAPIAuthorizationCodeFlowPlayerTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPlaylistsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPlaylistsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests.__allTests__SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowSearchTests.__allTests__SpotifyAPIAuthorizationCodeFlowSearchTests),
        testCase(SpotifyAPIAuthorizationCodeFlowShowTests.__allTests__SpotifyAPIAuthorizationCodeFlowShowTests),
        testCase(SpotifyAPIAuthorizationCodeFlowTrackTests.__allTests__SpotifyAPIAuthorizationCodeFlowTrackTests),
        testCase(SpotifyAPIAuthorizationCodeFlowUserProfileTests.__allTests__SpotifyAPIAuthorizationCodeFlowUserProfileTests),
        testCase(SpotifyAPIClientCredentialsFlowAlbumsTests.__allTests__SpotifyAPIClientCredentialsFlowAlbumsTests),
        testCase(SpotifyAPIClientCredentialsFlowArtistTests.__allTests__SpotifyAPIClientCredentialsFlowArtistTests),
        testCase(SpotifyAPIClientCredentialsFlowAuthorizationTests.__allTests__SpotifyAPIClientCredentialsFlowAuthorizationTests),
        testCase(SpotifyAPIClientCredentialsFlowBrowseTests.__allTests__SpotifyAPIClientCredentialsFlowBrowseTests),
        testCase(SpotifyAPIClientCredentialsFlowEpisodeTests.__allTests__SpotifyAPIClientCredentialsFlowEpisodeTests),
        testCase(SpotifyAPIClientCredentialsFlowErrorTests.__allTests__SpotifyAPIClientCredentialsFlowErrorTests),
        testCase(SpotifyAPIClientCredentialsFlowFollowTests.__allTests__SpotifyAPIClientCredentialsFlowFollowTests),
        testCase(SpotifyAPIClientCredentialsFlowMarketTests.__allTests__SpotifyAPIClientCredentialsFlowMarketTests),
        testCase(SpotifyAPIClientCredentialsFlowPlaylistsTests.__allTests__SpotifyAPIClientCredentialsFlowPlaylistsTests),
        testCase(SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests.__allTests__SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests),
        testCase(SpotifyAPIClientCredentialsFlowSearchTests.__allTests__SpotifyAPIClientCredentialsFlowSearchTests),
        testCase(SpotifyAPIClientCredentialsFlowShowTests.__allTests__SpotifyAPIClientCredentialsFlowShowTests),
        testCase(SpotifyAPIClientCredentialsFlowTrackTests.__allTests__SpotifyAPIClientCredentialsFlowTrackTests),
        testCase(SpotifyAPIClientCredentialsFlowUserProfileTests.__allTests__SpotifyAPIClientCredentialsFlowUserProfileTests),
        testCase(SpotifyIdentifierTests.__allTests__SpotifyIdentifierTests),
        testCase(SpotifyPlayerErrorCodingTests.__allTests__SpotifyPlayerErrorCodingTests),
    ]
}
#endif
