#if !canImport(ObjectiveC)
import XCTest

extension CodingAuthInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthInfoTests = [
        ("testCodingAuthInfo", testCodingAuthInfo),
    ]
}

extension CodingAuthorizationCodeFlowManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthorizationCodeFlowManagerTests = [
        ("testCodingAuthorizationCodeFlowManager", testCodingAuthorizationCodeFlowManager),
    ]
}

extension CodingAuthorizationCodeFlowPKCEManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingAuthorizationCodeFlowPKCEManagerTests = [
        ("testCodingAuthorizationCodeFlowManager", testCodingAuthorizationCodeFlowManager),
    ]
}

extension CodingClientCredentialsFlowManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingClientCredentialsFlowManagerTests = [
        ("testCodingClientCredentialsFlowManager", testCodingClientCredentialsFlowManager),
    ]
}

extension CodingCurrentlyPlayingContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingCurrentlyPlayingContextTests = [
        ("testCodingCurrentlyPlayingContext", testCodingCurrentlyPlayingContext),
    ]
}

extension CodingPlaybackRequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingPlaybackRequestTests = [
        ("testCodingPlaybackReqest", testCodingPlaybackReqest),
    ]
}

extension CodingTimeReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingTimeReferenceTests = [
        ("testCodingTimeReference", testCodingTimeReference),
    ]
}

extension ExampleContentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExampleContentTests = [
        ("testAadioAnalysis", testAadioAnalysis),
        ("testAlbums", testAlbums),
        ("testArtists", testArtists),
        ("testAudioFeatures", testAudioFeatures),
        ("testBrowse", testBrowse),
        ("testEpisodes", testEpisodes),
        ("testLibrary", testLibrary),
        ("testPlayer", testPlayer),
        ("testPlaylists", testPlaylists),
        ("testSearch", testSearch),
        ("testShows", testShows),
        ("testTracks", testTracks),
        ("testUserProfile", testUserProfile),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowAlbumsTests = [
        ("testAlbum", testAlbum),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowAuthorizationTests = [
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowManagerPlayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowManagerPlayerTests = [
        ("testAddToQueue", testAddToQueue),
        ("testPlayback", testPlayback),
        ("testPlayHistory", testPlayHistory),
        ("testPlayPause", testPlayPause),
        ("testRepeatMode", testRepeatMode),
        ("testShuffle", testShuffle),
        ("testSingleTrackPlayback", testSingleTrackPlayback),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests = [
        ("testAlbum", testAlbum),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests = [
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEManagerPlayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEManagerPlayerTests = [
        ("testAddToQueue", testAddToQueue),
        ("testPlayback", testPlayback),
        ("testPlayHistory", testPlayHistory),
        ("testPlayPause", testPlayPause),
        ("testRepeatMode", testRepeatMode),
        ("testShuffle", testShuffle),
        ("testSingleTrackPlayback", testSingleTrackPlayback),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests = [
        ("testCreatePlaylistAddRemoveReorderItems", testCreatePlaylistAddRemoveReorderItems),
        ("testCreatePlaylistAndAddTracksThenUnfollowIt", testCreatePlaylistAndAddTracksThenUnfollowIt),
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistCoverImage", testPlaylistCoverImage),
        ("testRemoveAllOccurencesFromPlaylist", testRemoveAllOccurencesFromPlaylist),
        ("testRemoveSpecificOccurencesFromPlaylist", testRemoveSpecificOccurencesFromPlaylist),
        ("testReplaceItemsInPlaylist", testReplaceItemsInPlaylist),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests = [
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowPlaylistsTests = [
        ("testCreatePlaylistAddRemoveReorderItems", testCreatePlaylistAddRemoveReorderItems),
        ("testCreatePlaylistAndAddTracksThenUnfollowIt", testCreatePlaylistAndAddTracksThenUnfollowIt),
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
        ("testPlaylistCoverImage", testPlaylistCoverImage),
        ("testRemoveAllOccurencesFromPlaylist", testRemoveAllOccurencesFromPlaylist),
        ("testRemoveSpecificOccurencesFromPlaylist", testRemoveSpecificOccurencesFromPlaylist),
        ("testReplaceItemsInPlaylist", testReplaceItemsInPlaylist),
    ]
}

extension SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests = [
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyAPIClientCredentialsFlowAlbumsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowAlbumsTests = [
        ("testAlbum", testAlbum),
        ("testAlbums", testAlbums),
        ("testTheLongestAlbumTracks", testTheLongestAlbumTracks),
    ]
}

extension SpotifyAPIClientCredentialsFlowArtistTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowArtistTests = [
        ("testArtist", testArtist),
        ("testArtistAlbums", testArtistAlbums),
        ("testArtistAlbumsSingles", testArtistAlbumsSingles),
        ("testArtists", testArtists),
        ("testArtistTopTracks", testArtistTopTracks),
        ("testRelatedArtists", testRelatedArtists),
    ]
}

extension SpotifyAPIClientCredentialsFlowAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowAuthorizationTests = [
        ("testDeauthorizeReauthorize", testDeauthorizeReauthorize),
    ]
}

extension SpotifyAPIClientCredentialsFlowPlaylistsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowPlaylistsTests = [
        ("testFilteredPlaylist", testFilteredPlaylist),
        ("testGetCrumbPlaylist", testGetCrumbPlaylist),
        ("testGetCrumbPlaylistTracks", testGetCrumbPlaylistTracks),
        ("testOtherUserCurrentPlaylists", testOtherUserCurrentPlaylists),
    ]
}

extension SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests = [
        ("testConcurrentTokensRefresh", testConcurrentTokensRefresh),
    ]
}

extension SpotifyIdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpotifyIdentifierTests = [
        ("testAlbumURIs", testAlbumURIs),
        ("testArtistURIs", testArtistURIs),
        ("testEpisodeURIs", testEpisodeURIs),
        ("testInvalidURIs", testInvalidURIs),
        ("testPlaylistURIs", testPlaylistURIs),
        ("testShowURIs", testShowURIs),
        ("testTrackURIs", testTrackURIs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodingAuthInfoTests.__allTests__CodingAuthInfoTests),
        testCase(CodingAuthorizationCodeFlowManagerTests.__allTests__CodingAuthorizationCodeFlowManagerTests),
        testCase(CodingAuthorizationCodeFlowPKCEManagerTests.__allTests__CodingAuthorizationCodeFlowPKCEManagerTests),
        testCase(CodingClientCredentialsFlowManagerTests.__allTests__CodingClientCredentialsFlowManagerTests),
        testCase(CodingCurrentlyPlayingContextTests.__allTests__CodingCurrentlyPlayingContextTests),
        testCase(CodingPlaybackRequestTests.__allTests__CodingPlaybackRequestTests),
        testCase(CodingTimeReferenceTests.__allTests__CodingTimeReferenceTests),
        testCase(ExampleContentTests.__allTests__ExampleContentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowAlbumsTests.__allTests__SpotifyAPIAuthorizationCodeFlowAlbumsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowArtistTests.__allTests__SpotifyAPIAuthorizationCodeFlowArtistTests),
        testCase(SpotifyAPIAuthorizationCodeFlowAuthorizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowAuthorizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowManagerPlayerTests.__allTests__SpotifyAPIAuthorizationCodeFlowManagerPlayerTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEAlbumsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEArtistTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEArtistTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEAuthorizationTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEManagerPlayerTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEManagerPlayerTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCEPlaylistsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests.__allTests__SpotifyAPIAuthorizationCodeFlowPKCERefreshTokensConcurrentTests),
        testCase(SpotifyAPIAuthorizationCodeFlowPlaylistsTests.__allTests__SpotifyAPIAuthorizationCodeFlowPlaylistsTests),
        testCase(SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests.__allTests__SpotifyAPIAuthorizationCodeFlowRefreshTokensConcurrentTests),
        testCase(SpotifyAPIClientCredentialsFlowAlbumsTests.__allTests__SpotifyAPIClientCredentialsFlowAlbumsTests),
        testCase(SpotifyAPIClientCredentialsFlowArtistTests.__allTests__SpotifyAPIClientCredentialsFlowArtistTests),
        testCase(SpotifyAPIClientCredentialsFlowAuthorizationTests.__allTests__SpotifyAPIClientCredentialsFlowAuthorizationTests),
        testCase(SpotifyAPIClientCredentialsFlowPlaylistsTests.__allTests__SpotifyAPIClientCredentialsFlowPlaylistsTests),
        testCase(SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests.__allTests__SpotifyAPIClientCredentialsFlowRefreshTokensConcurrentTests),
        testCase(SpotifyIdentifierTests.__allTests__SpotifyIdentifierTests),
    ]
}
#endif
